import {
  Home,
  LayoutTemplate,
  Setting06FreeIcons,
  Trash,
} from "@hugeicons/core-free-icons";
import { Theme } from "./types";

export const data = {
  user: {
    name: "Shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },

  navMain: [
    {
      title: "Home",
      url: "/dashboard",
      icon: Home,
    },
    {
      title: "Templates",
      url: "/templates",
      icon: LayoutTemplate,
    },
    {
      title: "Trash",
      url: "/trash",
      icon: Trash,
    },
    {
      title: "Settings",
      url: "/settings",
      icon: Setting06FreeIcons,
    },
  ],
};

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      type: "spring",
      stiffness: 100,
    },
  },
};

export const themes: Theme[] = [
  // --- 1-10: Básicos y Minimalistas ---
  {
    name: "Default Light",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#000000",
    backgroundColor: "#f0f0f0",
    slideBackgroundColor: "#ffffff",
    accentColor: "#3b82f6",
    navbarColor: "#ffffff",
    sidebarColor: "#f0f0f0",
    type: "light",
  },
  {
    name: "Default Dark",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#60a5fa",
    navbarColor: "#1e1e1e",
    sidebarColor: "#121212",
    type: "dark",
  },
  {
    name: "Clean White",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#333333",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f9f9f9",
    accentColor: "#10b981",
    navbarColor: "#ffffff",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Pitch Black",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#e0e0e0",
    backgroundColor: "#000000",
    slideBackgroundColor: "#0a0a0a",
    accentColor: "#f43f5e",
    navbarColor: "#000000",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Soft Gray",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#4a4a4a",
    backgroundColor: "#e5e7eb",
    slideBackgroundColor: "#f3f4f6",
    accentColor: "#8b5cf6",
    navbarColor: "#f3f4f6",
    sidebarColor: "#e5e7eb",
    type: "light",
  },
  {
    name: "Charcoal",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#f3f4f6",
    backgroundColor: "#374151",
    slideBackgroundColor: "#4b5563",
    accentColor: "#fbbf24",
    navbarColor: "#4b5563",
    sidebarColor: "#374151",
    type: "dark",
  },
  {
    name: "Warm Ivory",
    fontFamily: "'Lato', sans-serif",
    fontColor: "#4338ca",
    backgroundColor: "#fef3c7",
    slideBackgroundColor: "#fffbeb",
    accentColor: "#d97706",
    navbarColor: "#fffbeb",
    sidebarColor: "#fef3c7",
    type: "light",
  },
  {
    name: "Cool Slate",
    fontFamily: "'Lato', sans-serif",
    fontColor: "#f8fafc",
    backgroundColor: "#475569",
    slideBackgroundColor: "#64748b",
    accentColor: "#38bdf8",
    navbarColor: "#64748b",
    sidebarColor: "#475569",
    type: "dark",
  },
  {
    name: "Sepia Light",
    fontFamily: "'Merriweather', serif",
    fontColor: "#5c4033",
    backgroundColor: "#f4ecd8",
    slideBackgroundColor: "#fbf8f1",
    accentColor: "#c2410c",
    navbarColor: "#fbf8f1",
    sidebarColor: "#f4ecd8",
    type: "light",
  },
  {
    name: "Sepia Dark",
    fontFamily: "'Merriweather', serif",
    fontColor: "#d6c3b3",
    backgroundColor: "#43302b",
    slideBackgroundColor: "#5c4033",
    accentColor: "#fdba74",
    navbarColor: "#5c4033",
    sidebarColor: "#43302b",
    type: "dark",
  },

  // --- 11-20: Inspirados en la Naturaleza ---
  {
    name: "Forest Green",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#064e3b",
    backgroundColor: "#d1fae5",
    slideBackgroundColor: "#ecfdf5",
    accentColor: "#059669",
    navbarColor: "#ecfdf5",
    sidebarColor: "#d1fae5",
    type: "light",
  },
  {
    name: "Deep Woods",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#ecfdf5",
    backgroundColor: "#064e3b",
    slideBackgroundColor: "#065f46",
    accentColor: "#34d399",
    navbarColor: "#065f46",
    sidebarColor: "#064e3b",
    type: "dark",
  },
  {
    name: "Ocean Breeze",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#1e3a8a",
    backgroundColor: "#e0f2fe",
    slideBackgroundColor: "#f0f9ff",
    accentColor: "#0284c7",
    navbarColor: "#f0f9ff",
    sidebarColor: "#e0f2fe",
    type: "light",
  },
  {
    name: "Midnight Sea",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#e0f2fe",
    backgroundColor: "#1e3a8a",
    slideBackgroundColor: "#1e40af",
    accentColor: "#38bdf8",
    navbarColor: "#1e40af",
    sidebarColor: "#1e3a8a",
    type: "dark",
  },
  {
    name: "Desert Sand",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#78350f",
    backgroundColor: "#fef3c7",
    slideBackgroundColor: "#fffbeb",
    accentColor: "#b45309",
    navbarColor: "#fffbeb",
    sidebarColor: "#fef3c7",
    type: "light",
  },
  {
    name: "Canyon Night",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#fef3c7",
    backgroundColor: "#451a03",
    slideBackgroundColor: "#78350f",
    accentColor: "#fbbf24",
    navbarColor: "#78350f",
    sidebarColor: "#451a03",
    type: "dark",
  },
  {
    name: "Spring Flora",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#831843",
    backgroundColor: "#fce7f3",
    slideBackgroundColor: "#fdf2f8",
    accentColor: "#db2777",
    navbarColor: "#fdf2f8",
    sidebarColor: "#fce7f3",
    type: "light",
  },
  {
    name: "Autumn Leaves",
    fontFamily: "'Lora', serif",
    fontColor: "#451a03",
    backgroundColor: "#ffedd5",
    slideBackgroundColor: "#fff7ed",
    accentColor: "#ea580c",
    navbarColor: "#fff7ed",
    sidebarColor: "#ffedd5",
    type: "light",
  },
  {
    name: "Volcanic Ash",
    fontFamily: "'Oswald', sans-serif",
    fontColor: "#f87171",
    backgroundColor: "#1c1917",
    slideBackgroundColor: "#292524",
    accentColor: "#dc2626",
    navbarColor: "#292524",
    sidebarColor: "#1c1917",
    type: "dark",
  },
  {
    name: "Mossy Rock",
    fontFamily: "'Ubuntu', sans-serif",
    fontColor: "#ecfdf5",
    backgroundColor: "#27272a",
    slideBackgroundColor: "#3f3f46",
    accentColor: "#10b981",
    navbarColor: "#3f3f46",
    sidebarColor: "#27272a",
    type: "dark",
  },

  // --- 21-30: Temas Pastel ---
  {
    name: "Pastel Mint",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#ccfbf1",
    slideBackgroundColor: "#f0fdfa",
    accentColor: "#14b8a6",
    navbarColor: "#f0fdfa",
    sidebarColor: "#ccfbf1",
    type: "light",
  },
  {
    name: "Pastel Lilac",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#f3e8ff",
    slideBackgroundColor: "#faf5ff",
    accentColor: "#9333ea",
    navbarColor: "#faf5ff",
    sidebarColor: "#f3e8ff",
    type: "light",
  },
  {
    name: "Pastel Peach",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#ffedd5",
    slideBackgroundColor: "#fff7ed",
    accentColor: "#f97316",
    navbarColor: "#fff7ed",
    sidebarColor: "#ffedd5",
    type: "light",
  },
  {
    name: "Pastel Sky",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#e0f2fe",
    slideBackgroundColor: "#f0f9ff",
    accentColor: "#0ea5e9",
    navbarColor: "#f0f9ff",
    sidebarColor: "#e0f2fe",
    type: "light",
  },
  {
    name: "Pastel Lemon",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#fef9c3",
    slideBackgroundColor: "#fefce8",
    accentColor: "#eab308",
    navbarColor: "#fefce8",
    sidebarColor: "#fef9c3",
    type: "light",
  },
  {
    name: "Pastel Rose",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#334155",
    backgroundColor: "#ffe4e6",
    slideBackgroundColor: "#fff1f2",
    accentColor: "#e11d48",
    navbarColor: "#fff1f2",
    sidebarColor: "#ffe4e6",
    type: "light",
  },
  {
    name: "Dark Mint",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#ccfbf1",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e293b",
    accentColor: "#2dd4bf",
    navbarColor: "#1e293b",
    sidebarColor: "#0f172a",
    type: "dark",
  },
  {
    name: "Dark Lilac",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#e9d5ff",
    backgroundColor: "#171717",
    slideBackgroundColor: "#262626",
    accentColor: "#c084fc",
    navbarColor: "#262626",
    sidebarColor: "#171717",
    type: "dark",
  },
  {
    name: "Dark Peach",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#fed7aa",
    backgroundColor: "#1c1917",
    slideBackgroundColor: "#292524",
    accentColor: "#fb923c",
    navbarColor: "#292524",
    sidebarColor: "#1c1917",
    type: "dark",
  },
  {
    name: "Dark Sky",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#bae6fd",
    backgroundColor: "#1e1e1e",
    slideBackgroundColor: "#2d2d2d",
    accentColor: "#38bdf8",
    navbarColor: "#2d2d2d",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },

  // --- 31-40: Cyberpunk y Neón ---
  {
    name: "Cyber Neon",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#00ffcc",
    backgroundColor: "#0d0221",
    slideBackgroundColor: "#160436",
    accentColor: "#ff00ff",
    navbarColor: "#160436",
    sidebarColor: "#0d0221",
    type: "dark",
  },
  {
    name: "Synthwave",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#fce788",
    backgroundColor: "#241734",
    slideBackgroundColor: "#332244",
    accentColor: "#f222ff",
    navbarColor: "#332244",
    sidebarColor: "#241734",
    type: "dark",
  },
  {
    name: "Matrix Green",
    fontFamily: "'Courier New', monospace",
    fontColor: "#00ff00",
    backgroundColor: "#000000",
    slideBackgroundColor: "#0a0a0a",
    accentColor: "#00cc00",
    navbarColor: "#0a0a0a",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Neon Blue",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#00d0ff",
    backgroundColor: "#050b14",
    slideBackgroundColor: "#0b1524",
    accentColor: "#0055ff",
    navbarColor: "#0b1524",
    sidebarColor: "#050b14",
    type: "dark",
  },
  {
    name: "Hot Pink Night",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ff66b2",
    backgroundColor: "#1a000d",
    slideBackgroundColor: "#2a0015",
    accentColor: "#ff0066",
    navbarColor: "#2a0015",
    sidebarColor: "#1a000d",
    type: "dark",
  },
  {
    name: "Toxic Waste",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#ccff00",
    backgroundColor: "#111111",
    slideBackgroundColor: "#1a1a1a",
    accentColor: "#99cc00",
    navbarColor: "#1a1a1a",
    sidebarColor: "#111111",
    type: "dark",
  },
  {
    name: "Vaporwave Light",
    fontFamily: "'Arial', sans-serif",
    fontColor: "#330066",
    backgroundColor: "#ffb3d9",
    slideBackgroundColor: "#ffcce6",
    accentColor: "#00cccc",
    navbarColor: "#ffcce6",
    sidebarColor: "#ffb3d9",
    type: "light",
  },
  {
    name: "Outrun Retro",
    fontFamily: "'Press Start 2P', cursive",
    fontColor: "#ffcc00",
    backgroundColor: "#0b001a",
    slideBackgroundColor: "#160033",
    accentColor: "#ff0055",
    navbarColor: "#160033",
    sidebarColor: "#0b001a",
    type: "dark",
  },
  {
    name: "Neon Orange",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#ff9900",
    backgroundColor: "#1a0f00",
    slideBackgroundColor: "#2a1800",
    accentColor: "#ff5500",
    navbarColor: "#2a1800",
    sidebarColor: "#1a0f00",
    type: "dark",
  },
  {
    name: "Laser Red",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ff3333",
    backgroundColor: "#120000",
    slideBackgroundColor: "#220000",
    accentColor: "#ff0000",
    navbarColor: "#220000",
    sidebarColor: "#120000",
    type: "dark",
  },

  // --- 41-50: Estilos "Material Design" ---
  {
    name: "Material Indigo",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#f5f5f6",
    slideBackgroundColor: "#ffffff",
    accentColor: "#3f51b5",
    navbarColor: "#3f51b5", // Color en Navbar
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Material Teal",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#eceff1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#009688",
    navbarColor: "#009688",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Material Crimson",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#fafafa",
    slideBackgroundColor: "#ffffff",
    accentColor: "#f44336",
    navbarColor: "#f44336",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Material Amber",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#fff8e1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ffc107",
    navbarColor: "#ffc107",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Material Deep Purple",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#ede7f6",
    slideBackgroundColor: "#ffffff",
    accentColor: "#673ab7",
    navbarColor: "#673ab7",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Material Dark Indigo",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#7986cb",
    navbarColor: "#1a237e",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },
  {
    name: "Material Dark Teal",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#4db6ac",
    navbarColor: "#004d40",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },
  {
    name: "Material Dark Red",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#e57373",
    navbarColor: "#b71c1c",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },
  {
    name: "Material Dark Green",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#81c784",
    navbarColor: "#1b5e20",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },
  {
    name: "Material Dark Orange",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#121212",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#ffb74d",
    navbarColor: "#e65100",
    sidebarColor: "#1e1e1e",
    type: "dark",
  },

  // --- 51-60: Estilos Corporativos y Profesionales ---
  {
    name: "Corporate Blue",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    fontColor: "#333333",
    backgroundColor: "#f4f7f6",
    slideBackgroundColor: "#ffffff",
    accentColor: "#0056b3",
    navbarColor: "#ffffff",
    sidebarColor: "#f4f7f6",
    type: "light",
  },
  {
    name: "Executive Gray",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    fontColor: "#1a1a1a",
    backgroundColor: "#eef2f5",
    slideBackgroundColor: "#ffffff",
    accentColor: "#495057",
    navbarColor: "#ffffff",
    sidebarColor: "#eef2f5",
    type: "light",
  },
  {
    name: "Banking Green",
    fontFamily: "'Arial', sans-serif",
    fontColor: "#222222",
    backgroundColor: "#f8f9fa",
    slideBackgroundColor: "#ffffff",
    accentColor: "#28a745",
    navbarColor: "#ffffff",
    sidebarColor: "#f8f9fa",
    type: "light",
  },
  {
    name: "Agency Black",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#000000",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f1f1f1",
    accentColor: "#000000",
    navbarColor: "#ffffff",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Startup Purple",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#1e1e2f",
    backgroundColor: "#f5f6fa",
    slideBackgroundColor: "#ffffff",
    accentColor: "#6c5ce7",
    navbarColor: "#ffffff",
    sidebarColor: "#f5f6fa",
    type: "light",
  },
  {
    name: "Corporate Night Blue",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    fontColor: "#e0e0e0",
    backgroundColor: "#0d1b2a",
    slideBackgroundColor: "#1b263b",
    accentColor: "#415a77",
    navbarColor: "#1b263b",
    sidebarColor: "#0d1b2a",
    type: "dark",
  },
  {
    name: "Executive Dark Gray",
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    fontColor: "#d3d3d3",
    backgroundColor: "#212529",
    slideBackgroundColor: "#343a40",
    accentColor: "#6c757d",
    navbarColor: "#343a40",
    sidebarColor: "#212529",
    type: "dark",
  },
  {
    name: "Finance Dark",
    fontFamily: "'Arial', sans-serif",
    fontColor: "#f8f9fa",
    backgroundColor: "#1b4332",
    slideBackgroundColor: "#2d6a4f",
    accentColor: "#52b788",
    navbarColor: "#2d6a4f",
    sidebarColor: "#1b4332",
    type: "dark",
  },
  {
    name: "Agency Night",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#000000",
    slideBackgroundColor: "#111111",
    accentColor: "#aaaaaa",
    navbarColor: "#111111",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Tech Startup Dark",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#f1f2f6",
    backgroundColor: "#2f3542",
    slideBackgroundColor: "#57606f",
    accentColor: "#7bed9f",
    navbarColor: "#57606f",
    sidebarColor: "#2f3542",
    type: "dark",
  },

  // --- 61-70: Elegantes y con Serifas ---
  {
    name: "Classic Print",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#111111",
    backgroundColor: "#fdfbf7",
    slideBackgroundColor: "#ffffff",
    accentColor: "#8b0000",
    navbarColor: "#ffffff",
    sidebarColor: "#fdfbf7",
    type: "light",
  },
  {
    name: "Novel Page",
    fontFamily: "'Georgia', serif",
    fontColor: "#2b2b2b",
    backgroundColor: "#f5f5dc",
    slideBackgroundColor: "#fffff0",
    accentColor: "#556b2f",
    navbarColor: "#fffff0",
    sidebarColor: "#f5f5dc",
    type: "light",
  },
  {
    name: "Editorial",
    fontFamily: "'Didot', serif",
    fontColor: "#000000",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#fafafa",
    accentColor: "#000080",
    navbarColor: "#ffffff",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Vintage Card",
    fontFamily: "'Courier New', monospace",
    fontColor: "#3e2723",
    backgroundColor: "#d7ccc8",
    slideBackgroundColor: "#efebe9",
    accentColor: "#5d4037",
    navbarColor: "#efebe9",
    sidebarColor: "#d7ccc8",
    type: "light",
  },
  {
    name: "Royal Light",
    fontFamily: "'Cinzel', serif",
    fontColor: "#4b0082",
    backgroundColor: "#f3e5f5",
    slideBackgroundColor: "#faf8fc",
    accentColor: "#d4af37",
    navbarColor: "#faf8fc",
    sidebarColor: "#f3e5f5",
    type: "light",
  },
  {
    name: "Midnight Library",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#dcdcdc",
    backgroundColor: "#2b2b2b",
    slideBackgroundColor: "#383838",
    accentColor: "#c0a080",
    navbarColor: "#383838",
    sidebarColor: "#2b2b2b",
    type: "dark",
  },
  {
    name: "Antique Ink",
    fontFamily: "'Georgia', serif",
    fontColor: "#e6e6fa",
    backgroundColor: "#191970",
    slideBackgroundColor: "#202050",
    accentColor: "#ffeedd",
    navbarColor: "#202050",
    sidebarColor: "#191970",
    type: "dark",
  },
  {
    name: "Dark Editorial",
    fontFamily: "'Didot', serif",
    fontColor: "#ffffff",
    backgroundColor: "#000000",
    slideBackgroundColor: "#1a1a1a",
    accentColor: "#ffd700",
    navbarColor: "#000000",
    sidebarColor: "#1a1a1a",
    type: "dark",
  },
  {
    name: "Burnt Manuscript",
    fontFamily: "'Courier New', monospace",
    fontColor: "#ffdead",
    backgroundColor: "#3e2723",
    slideBackgroundColor: "#4e342e",
    accentColor: "#d84315",
    navbarColor: "#4e342e",
    sidebarColor: "#3e2723",
    type: "dark",
  },
  {
    name: "Royal Dark",
    fontFamily: "'Cinzel', serif",
    fontColor: "#e6e6fa",
    backgroundColor: "#240046",
    slideBackgroundColor: "#3c096c",
    accentColor: "#ff9e00",
    navbarColor: "#3c096c",
    sidebarColor: "#240046",
    type: "dark",
  },

  // --- 71-80: Inspirados en Entornos de Desarrollo (IDEs) ---
  {
    name: "Dracula",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#f8f8f2",
    backgroundColor: "#282a36",
    slideBackgroundColor: "#44475a",
    accentColor: "#ff79c6",
    navbarColor: "#44475a",
    sidebarColor: "#282a36",
    type: "dark",
  },
  {
    name: "Monokai",
    fontFamily: "'Consolas', monospace",
    fontColor: "#f8f8f2",
    backgroundColor: "#272822",
    slideBackgroundColor: "#3e3d32",
    accentColor: "#a6e22e",
    navbarColor: "#3e3d32",
    sidebarColor: "#272822",
    type: "dark",
  },
  {
    name: "Nord",
    fontFamily: "'Source Code Pro', monospace",
    fontColor: "#d8dee9",
    backgroundColor: "#2e3440",
    slideBackgroundColor: "#3b4252",
    accentColor: "#88c0d0",
    navbarColor: "#3b4252",
    sidebarColor: "#2e3440",
    type: "dark",
  },
  {
    name: "Solarized Light Code",
    fontFamily: "'Menlo', monospace",
    fontColor: "#657b83",
    backgroundColor: "#fdf6e3",
    slideBackgroundColor: "#eee8d5",
    accentColor: "#268bd2",
    navbarColor: "#eee8d5",
    sidebarColor: "#fdf6e3",
    type: "light",
  },
  {
    name: "Solarized Dark Code",
    fontFamily: "'Menlo', monospace",
    fontColor: "#839496",
    backgroundColor: "#002b36",
    slideBackgroundColor: "#073642",
    accentColor: "#2aa198",
    navbarColor: "#073642",
    sidebarColor: "#002b36",
    type: "dark",
  },
  {
    name: "Gruvbox Light",
    fontFamily: "'Inconsolata', monospace",
    fontColor: "#3c3836",
    backgroundColor: "#fbf1c7",
    slideBackgroundColor: "#ebdbb2",
    accentColor: "#9d0006",
    navbarColor: "#ebdbb2",
    sidebarColor: "#fbf1c7",
    type: "light",
  },
  {
    name: "Gruvbox Dark",
    fontFamily: "'Inconsolata', monospace",
    fontColor: "#ebdbb2",
    backgroundColor: "#282828",
    slideBackgroundColor: "#3c3836",
    accentColor: "#fe8019",
    navbarColor: "#3c3836",
    sidebarColor: "#282828",
    type: "dark",
  },
  {
    name: "One Dark",
    fontFamily: "'Consolas', monospace",
    fontColor: "#abb2bf",
    backgroundColor: "#282c34",
    slideBackgroundColor: "#3e4451",
    accentColor: "#61afef",
    navbarColor: "#3e4451",
    sidebarColor: "#282c34",
    type: "dark",
  },
  {
    name: "Github Light",
    fontFamily: "'System UI', sans-serif",
    fontColor: "#24292e",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#f6f8fa",
    accentColor: "#0366d6",
    navbarColor: "#f6f8fa",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "Github Dark",
    fontFamily: "'System UI', sans-serif",
    fontColor: "#c9d1d9",
    backgroundColor: "#0d1117",
    slideBackgroundColor: "#161b22",
    accentColor: "#58a6ff",
    navbarColor: "#161b22",
    sidebarColor: "#0d1117",
    type: "dark",
  },

  // --- 81-90: Tonos Joya (Jewel Tones) ---
  {
    name: "Ruby Light",
    fontFamily: "'Lora', serif",
    fontColor: "#4a0404",
    backgroundColor: "#ffecec",
    slideBackgroundColor: "#fff5f5",
    accentColor: "#b91c1c",
    navbarColor: "#fff5f5",
    sidebarColor: "#ffecec",
    type: "light",
  },
  {
    name: "Ruby Dark",
    fontFamily: "'Lora', serif",
    fontColor: "#fecaca",
    backgroundColor: "#450a0a",
    slideBackgroundColor: "#7f1d1d",
    accentColor: "#ef4444",
    navbarColor: "#7f1d1d",
    sidebarColor: "#450a0a",
    type: "dark",
  },
  {
    name: "Sapphire Light",
    fontFamily: "'Oswald', sans-serif",
    fontColor: "#0b2046",
    backgroundColor: "#eef2ff",
    slideBackgroundColor: "#f5f7ff",
    accentColor: "#1d4ed8",
    navbarColor: "#f5f7ff",
    sidebarColor: "#eef2ff",
    type: "light",
  },
  {
    name: "Sapphire Dark",
    fontFamily: "'Oswald', sans-serif",
    fontColor: "#bfdbfe",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e3a8a",
    accentColor: "#3b82f6",
    navbarColor: "#1e3a8a",
    sidebarColor: "#0f172a",
    type: "dark",
  },
  {
    name: "Emerald Light",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#022c22",
    backgroundColor: "#ecfdf5",
    slideBackgroundColor: "#f4fdf9",
    accentColor: "#047857",
    navbarColor: "#f4fdf9",
    sidebarColor: "#ecfdf5",
    type: "light",
  },
  {
    name: "Emerald Dark",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#a7f3d0",
    backgroundColor: "#022c22",
    slideBackgroundColor: "#064e3b",
    accentColor: "#10b981",
    navbarColor: "#064e3b",
    sidebarColor: "#022c22",
    type: "dark",
  },
  {
    name: "Amethyst Light",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#2e1065",
    backgroundColor: "#f5f3ff",
    slideBackgroundColor: "#faf9ff",
    accentColor: "#6d28d9",
    navbarColor: "#faf9ff",
    sidebarColor: "#f5f3ff",
    type: "light",
  },
  {
    name: "Amethyst Dark",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#ddd6fe",
    backgroundColor: "#2e1065",
    slideBackgroundColor: "#4c1d95",
    accentColor: "#8b5cf6",
    navbarColor: "#4c1d95",
    sidebarColor: "#2e1065",
    type: "dark",
  },
  {
    name: "Topaz Light",
    fontFamily: "'Work Sans', sans-serif",
    fontColor: "#422006",
    backgroundColor: "#fef3c7",
    slideBackgroundColor: "#fffbeb",
    accentColor: "#d97706",
    navbarColor: "#fffbeb",
    sidebarColor: "#fef3c7",
    type: "light",
  },
  {
    name: "Topaz Dark",
    fontFamily: "'Work Sans', sans-serif",
    fontColor: "#fde68a",
    backgroundColor: "#422006",
    slideBackgroundColor: "#78350f",
    accentColor: "#f59e0b",
    navbarColor: "#78350f",
    sidebarColor: "#422006",
    type: "dark",
  },

  // --- 91-98: Temas de Alto Contraste y Accesibilidad ---
  {
    name: "High Contrast Black on White",
    fontFamily: "Arial, sans-serif",
    fontColor: "#000000",
    backgroundColor: "#ffffff",
    slideBackgroundColor: "#ffffff",
    accentColor: "#0000ff", // Azul puro para enlaces
    navbarColor: "#ffffff",
    sidebarColor: "#ffffff",
    type: "light",
  },
  {
    name: "High Contrast White on Black",
    fontFamily: "Arial, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#000000",
    slideBackgroundColor: "#000000",
    accentColor: "#ffff00", // Amarillo puro para destacar
    navbarColor: "#000000",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "High Contrast Yellow on Black",
    fontFamily: "Verdana, sans-serif",
    fontColor: "#ffff00",
    backgroundColor: "#000000",
    slideBackgroundColor: "#000000",
    accentColor: "#00ff00",
    navbarColor: "#000000",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Dyslexia Friendly Light",
    fontFamily: "'OpenDyslexic', 'Comic Sans MS', sans-serif",
    fontColor: "#000000",
    backgroundColor: "#ffffcc", // Fondo amarillo pálido reduce fatiga
    slideBackgroundColor: "#ffffff",
    accentColor: "#0000cc",
    navbarColor: "#ffffff",
    sidebarColor: "#ffffcc",
    type: "light",
  },
  {
    name: "Dyslexia Friendly Dark",
    fontFamily: "'OpenDyslexic', 'Comic Sans MS', sans-serif",
    fontColor: "#eeeeee",
    backgroundColor: "#1a1a1a",
    slideBackgroundColor: "#2a2a2a",
    accentColor: "#66ccff",
    navbarColor: "#2a2a2a",
    sidebarColor: "#1a1a1a",
    type: "dark",
  },
  {
    name: "Monochrome Light",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#000000",
    backgroundColor: "#e0e0e0",
    slideBackgroundColor: "#f5f5f5",
    accentColor: "#555555",
    navbarColor: "#f5f5f5",
    sidebarColor: "#e0e0e0",
    type: "light",
  },
  {
    name: "Monochrome Dark",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#111111",
    slideBackgroundColor: "#222222",
    accentColor: "#aaaaaa",
    navbarColor: "#222222",
    sidebarColor: "#111111",
    type: "dark",
  },
  {
    name: "Midnight Blue High Contrast",
    fontFamily: "Tahoma, sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#000033",
    slideBackgroundColor: "#000066",
    accentColor: "#00ffff", // Cyan puro
    navbarColor: "#000066",
    sidebarColor: "#000033",
    type: "dark",
  },
];

export const CreatePageCard = [
  {
    title: "Use a",
    highlightedText: "Template",
    description: "Write a prompt and leave everything else for us to handle.",
    type: "template",
  },
  {
    title: "Generate with",
    highlightedText: "Codex AI",
    description: "Write a prompt and leave everything else for us to handle.",
    type: "codex-ai",
    highlight: true,
  },
  {
    title: "Start from",
    highlightedText: "Scratch",
    description: "Write a prompt and leave everything else for us to handle.",
    type: "create-scratch",
  },
];
